version: '3.8'

services:
  tracy-be:
    image: auroraphtgrp/tracy-be:latest
    build:
      context: .
    container_name: tracy-be
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5439/tracy?schema=public
      - BACKEND_DOMAIN=http://host.docker.internal:3333
      - BACKEND_PORT=3333
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=codevjp001@gmail.com
      - MAIL_PASSWORD=qurr ulsq esyl zhwb
      - JWT_ACCESS_TOKEN_SECRET_KEY=1231323123213213
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=10d
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=10d
      - JWT_REFRESH_TOKEN_SECRET_KEY=123123123123123
      - JWT_FORGOT_PASSWORD_TOKEN_SECRET_KEY=123123123123
      - JWT_FORGOT_PASSWORD_TOKEN_EXPIRATION_TIME=10d
      - JWT_ACCEPTED_TOKEN_SECRET_KEY=123123123123
      - JWT_ACCEPTED_TOKEN_EXPIRATION_TIME=3d
      - JWT_VERIFY_EMAIL_TOKEN_SECRET_KEY=1231233
      - JWT_VERIFY_EMAIL_TOKEN_EXPIRATION_TIME=10d
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6444
      - TTL=60
      - CACHE_MAX=1000
      - REDIS_PASSWORD=redis

    extra_hosts:
      - "host.docker.internal:host-gateway"
